apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-monitoring-external-leader-example-monitoring-external-leader-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /leader
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ck-master-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-monitoring-external-leader-example-monitoring-external-leader-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /leader
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ck-minion-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-monitoring-external-leader-example-monitoring-external-leader-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /leader
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ck-master-3
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-monitoring-external-leader-example-monitoring-external-leader-0
spec:
  storageClassName: local-storage
  volumeName: example-monitoring-external-leader-example-monitoring-external-leader-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-monitoring-external-leader-example-monitoring-external-leader-1
spec:
  storageClassName: local-storage
  volumeName: example-monitoring-external-leader-example-monitoring-external-leader-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-monitoring-external-leader-example-monitoring-external-leader-2
spec:
  storageClassName: local-storage
  volumeName: example-monitoring-external-leader-example-monitoring-external-leader-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
