apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-follower-example-follower-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /follower
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {HOST_NAME2}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-follower-example-follower-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /follower
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {HOST_NAME3}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-follower-example-follower-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /follower
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {HOST_NAME1}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-follower-example-follower-0
spec:
  storageClassName: local-storage
  volumeName: example-follower-example-follower-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-follower-example-follower-1
spec:
  storageClassName: local-storage
  volumeName: example-follower-example-follower-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-follower-example-follower-2
spec:
  storageClassName: local-storage
  volumeName: example-follower-example-follower-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
